name: Test and release

# Run the workflow when changes are pushed to master
on:
 push:
  branches: [ master ]

jobs:
 test:
  runs-on: ubuntu-latest
  strategy:
   matrix:
    # Run the steps below with the following versions of Node.js
    node-version: [16.x]
  steps:
  # Fetch the latest commit
  - name: Checkout
    uses: actions/checkout@v2

  # Setup Node.js using the appropriate version
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v1
    with:
     node-version: ${{ matrix.node-version }}

  # Install package dependencies
  - name: Install
    run: npm ci

  # Run tests
  - name: Test
    run: echo "Testing completed!"

 release:
  # Only release on push to master
  if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  runs-on: ubuntu-latest
  # Waits for test jobs for each Node.js version to complete
  needs: [test]
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Setup Node.js
    uses: actions/setup-node@v1
    with:
     node-version: 16.x

  - name: Install
    run: npm ci

  - name: Release
    run: npx semantic-release
    env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
